### PR TITLE
If no file provided defer file.Close() causes panic.

### PR DESCRIPTION
**Pull request by andyb**
I've moved the defer call after error check to prevent panic when file not found.

### CODE REVIEW

**Comment by mish15** [comment]
@andyb thanks for the PR. From memory I put it there for a reason. I think it's possible to have a file and an error (?), which would cause a mem leak. Will have a look in the morning. Cheers!

**Comment by andyb** [comment]
No problem, thanks for the useful package! If it needs to be there maybe a nil check will suffice to stop the panic. Let me know if you need me to change anything.

**Comment by mish15** [comment]
Yep no worries. Definitely need to get rid of the panic! Will have a play
in the morning.

On Thursday, 26 February 2015, Andy Britcliffe <notifications@github.com>
wrote:

> No problem, thanks for the useful package! If it needs to be there maybe a
> nil check will suffice to stop the panic. Let me know if you need me to
> change anything.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sajari/sajari-convert/pull/6#issuecomment-76161858>.
>


-- 
*Hamish Ogilvy*
Sajari Pty Ltd
*t:  +61 (*0) 414 658 353  |  *e: *hogilvy@sajari.com
*w:*  www.sajari.com

**Comment by mish15** [comment]
Closing in favour of 61f9ca28dc4dcaf251ba829f170a99fbbf38e72b

**Pull request closed without merging**
